# """
# Common dream symbols and their categories for enhanced extraction.
# These supplement spaCy's NER with dream-specific vocabulary.
# """

# Dream-specific symbols grouped by category
DREAM_SYMBOLS = {
    "falling": "anxiety",
    "flying": "freedom",
    "teeth falling out": "insecurity",
    "teeth": "insecurity",
    "being chased": "avoidance",
    "chased": "avoidance",
    "running": "avoidance",
    "naked in public": "vulnerability",
    "naked": "vulnerability",
    "water": "emotion",
    "ocean": "emotion",
    "river": "emotion",
    "lake": "emotion",
    "flood": "overwhelm",
    "drowning": "overwhelm",
    "fire": "transformation",
    "burning": "transformation",
    "death": "change",
    "dying": "change",
    "funeral": "change",
    "snake": "hidden_threat",
    "spider": "anxiety",
    "dog": "loyalty",
    "cat": "independence",
    "bird": "freedom",
    "fish": "subconscious",
    "horse": "power",
    "wolf": "instinct",
    "bear": "strength",
    "lion": "courage",
    "house": "self",
    "room": "self",
    "door": "opportunity",
    "window": "perspective",
    "stairs": "progress",
    "elevator": "progress",
    "bridge": "transition",
    "road": "life_path",
    "path": "life_path",
    "forest": "unknown",
    "mountain": "challenge",
    "cave": "subconscious",
    "garden": "growth",
    "tree": "growth",
    "flower": "beauty",
    "baby": "new_beginning",
    "child": "innocence",
    "mother": "nurturing",
    "father": "authority",
    "stranger": "unknown_aspect",
    "shadow": "hidden_self",
    "mirror": "self_reflection",
    "clock": "time_pressure",
    "phone": "communication",
    "car": "control",
    "driving": "control",
    "crash": "loss_of_control",
    "train": "life_journey",
    "airplane": "ambition",
    "boat": "emotional_journey",
    "school": "learning",
    "exam": "self_evaluation",
    "test": "self_evaluation",
    "hospital": "healing",
    "prison": "restriction",
    "trapped": "restriction",
    "lost": "confusion",
    "maze": "confusion",
    "key": "solution",
    "money": "self_worth",
    "gold": "value",
    "diamond": "clarity",
    "blood": "life_force",
    "rain": "cleansing",
    "storm": "emotional_turmoil",
    "snow": "purity",
    "sun": "consciousness",
    "moon": "intuition",
    "stars": "hope",
    "darkness": "unknown",
    "light": "awareness",
    "wedding": "commitment",
    "pregnancy": "creativity",
    "war": "inner_conflict",
    "fighting": "inner_conflict",
    "knife": "conflict",
    "sword": "power",
    "gun": "aggression",
    "monster": "fear",
    "ghost": "past",
    "zombie": "mindlessness",
    "vampire": "energy_drain",
    "angel": "guidance",
    "devil": "temptation",
    "god": "higher_self",
    "heaven": "aspiration",
    "hell": "suffering",
    "food": "nourishment",
    "eating": "nourishment",
    "hunger": "desire",
    "desert": "isolation",
    "island": "isolation",
    "crowd": "social_pressure",
    "party": "social_life",
    "music": "harmony",
    "singing": "expression",
    "dancing": "freedom",
    "painting": "creativity",
    "book": "knowledge",
    "letter": "message",
    "map": "direction",
    "compass": "guidance",
}

# Broader thematic categories
SYMBOL_CATEGORIES = {
    "anxiety": "Anxiety & Stress",
    "freedom": "Freedom & Liberation",
    "insecurity": "Insecurity & Self-doubt",
    "avoidance": "Avoidance & Escape",
    "vulnerability": "Vulnerability",
    "emotion": "Emotions & Feelings",
    "overwhelm": "Feeling Overwhelmed",
    "transformation": "Transformation & Change",
    "change": "Endings & New Beginnings",
    "hidden_threat": "Hidden Threats",
    "subconscious": "Subconscious Mind",
    "power": "Power & Strength",
    "instinct": "Instincts & Primal Nature",
    "strength": "Inner Strength",
    "courage": "Courage",
    "self": "Self & Identity",
    "opportunity": "Opportunity",
    "perspective": "Perspective & Insight",
    "progress": "Progress & Growth",
    "transition": "Life Transitions",
    "life_path": "Life Direction",
    "unknown": "The Unknown",
    "challenge": "Challenges & Obstacles",
    "growth": "Personal Growth",
    "beauty": "Beauty & Appreciation",
    "new_beginning": "New Beginnings",
    "innocence": "Innocence & Inner Child",
    "nurturing": "Nurturing & Care",
    "authority": "Authority & Guidance",
    "unknown_aspect": "Unknown Aspects of Self",
    "hidden_self": "Shadow Self",
    "self_reflection": "Self-Reflection",
    "time_pressure": "Time Pressure",
    "communication": "Communication",
    "control": "Control & Direction",
    "loss_of_control": "Loss of Control",
    "life_journey": "Life Journey",
    "ambition": "Ambition & Goals",
    "emotional_journey": "Emotional Journey",
    "learning": "Learning & Growth",
    "self_evaluation": "Self-Evaluation",
    "healing": "Healing",
    "restriction": "Feeling Restricted",
    "confusion": "Confusion & Uncertainty",
    "solution": "Solutions & Answers",
    "self_worth": "Self-Worth",
    "value": "Value & Worth",
    "clarity": "Clarity",
    "life_force": "Vitality",
    "cleansing": "Cleansing & Renewal",
    "emotional_turmoil": "Emotional Turmoil",
    "purity": "Purity & Fresh Start",
    "consciousness": "Consciousness & Awareness",
    "intuition": "Intuition",
    "hope": "Hope & Inspiration",
    "awareness": "Awareness & Enlightenment",
    "commitment": "Commitment",
    "creativity": "Creativity",
    "inner_conflict": "Inner Conflict",
    "conflict": "Conflict",
    "aggression": "Aggression",
    "fear": "Fear",
    "past": "The Past",
    "mindlessness": "Mindlessness & Routine",
    "energy_drain": "Energy Drain",
    "guidance": "Guidance",
    "temptation": "Temptation",
    "higher_self": "Higher Self",
    "aspiration": "Aspirations",
    "suffering": "Suffering",
    "nourishment": "Nourishment & Fulfillment",
    "desire": "Desire & Longing",
    "isolation": "Isolation & Loneliness",
    "social_pressure": "Social Pressure",
    "social_life": "Social Life",
    "harmony": "Harmony",
    "expression": "Self-Expression",
    "knowledge": "Knowledge & Wisdom",
    "message": "Messages & Communication",
    "direction": "Direction & Purpose",
}


def get_symbol_info(symbol: str) -> dict | None:
    """Look up a dream symbol and return its category info."""
    symbol_lower = symbol.lower()
    if symbol_lower in DREAM_SYMBOLS:
        category_key = DREAM_SYMBOLS[symbol_lower]
        return {
            "symbol": symbol_lower,
            "category_key": category_key,
            "category_name": SYMBOL_CATEGORIES.get(category_key, category_key),
        }
    return None


def get_all_symbol_keywords() -> list[str]:
    """Return all known dream symbol keywords for matching."""
    return list(DREAM_SYMBOLS.keys())